# Taps
tap "homebrew/bundle"

# CLI tools
brew "bat"
brew "caddy"
brew "cmake"
brew "coreutils"
brew "delta"
brew "deno"
brew "direnv"
brew "dnsmasq"
brew "docker"
brew "fd"
brew "ffmpeg"
brew "fzf"
brew "gh"
brew "git"
brew "git-lfs"
brew "go"
brew "grc"
brew "helix"
brew "hexedit"
brew "highlight"
brew "imagemagick"
brew "jq"
brew "neovim"
brew "python3"
brew "ripgrep"
brew "rsync"
brew "rustup"
brew "shellcheck"
brew "sqlite"
brew "stow"
brew "tmux"
brew "tree-sitter"
brew "vim"
brew "zig"
brew "zoxide"
brew "zsh"
brew "zsh-completions"

# GUI Apps
cask "1password-cli"
cask "arc"
cask "betterdisplay"
cask "blender"
cask "chatgpt"
cask "discord"
cask "dropbox"
cask "firefox"
cask "firefox@nightly"
cask "ghostty"
cask "github"
cask "google-chrome"
cask "home-assistant"
cask "keka"
cask "obsidian"
cask "parsec"
cask "plex"
cask "pop"
cask "raycast"
cask "setapp"
cask "signal"
cask "slack"
cask "spotify"
cask "steam"
cask "tableplus"
cask "ticktick"
cask "tuple"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "zed@preview"
cask "zoom"

# Fonts
cask "font-0xproto-nerd-font"
cask "font-fontawesome"
cask "font-iosevka-nerd-font"
cask "font-iosevka-term-nerd-font"
cask "font-iosevka-term-slab-nerd-font"

# Mac App Store
mas "NextDNS", id: 1464122853