#!/bin/bash

xrdb -merge -I$HOME $HOME/.Xresources-96
DPI="$(xrdb -query | grep 'Xft.dpi:' | awk '{ print $2 }')"
xrandr --dpi "$DPI"

# Also set in /etc/lightdm/lightdm.conf
xset r rate 200 20
# Also set in /etc/X11/xorg.conf.d/00-keyboard.conf
setxkbmap -option ctrl:nocaps

pkill -9 dunst
