#!/bin/bash

if [[ "${BLOCK_BUTTON}" -eq 4 ]]; then
  amixer -q sset Capture 5%+
elif [[ "${BLOCK_BUTTON}" -eq 3 ]]; then
  amixer -q sset Capture toggle
elif [[ "${BLOCK_BUTTON}" -eq 5 ]]; then
  amixer -q sset Capture 5%-
fi

statusLine=$(amixer get Capture | tail -n 1)
status=$(echo "${statusLine}" | grep -wo "on")
volume=$(echo "${statusLine}" | awk -F ' ' '{print $5}' | tr -d '[]%')

if [[ "${status}" == "on" ]]; then
  echo "${volume}%"
  echo "${volume}%"
else
  echo "off"
  echo "off"
fi
