#!/bin/bash

IP_ADDRESS=$(ip route get 1 | awk '{print $7;exit}')

if [[ "${IP_ADDRESS}" != "" ]]; then
  echo ""
  echo "online"
  echo "#C3E88D"
else
  echo " "
  echo "offline"
  echo "#F07178"
fi
