#!/bin/bash

IP_ADDRESS=$(ip route get 1 | awk '{print $7;exit}')

if [[ "${IP_ADDRESS}" != "" ]]; then
  echo " ${IP_ADDRESS}"
  echo "${IP_ADDRESS}"
  echo "#a8e285"
else
  echo " offline"
  echo "offline"
  echo "#dd9680"
fi
