#!/bin/bash

if [[ "${BLOCK_BUTTON}" -eq 1 ]]; then
  notify-send Packages "$(checkupdates)"
fi

count=$(checkupdates | wc -l)

if [ "$count" -gt 0 ]; then
  echo " $count"
  echo " $count"
  echo "#C3E88D"
else
  echo ""
  echo ""
  echo "#314549"
fi
