#!/bin/bash

xrdb -merge -I$HOME $HOME/.Xresources-mobile
DPI="$(xrdb -query | grep 'Xft.dpi:' | awk '{ print $2 }')"
xrandr --dpi "$DPI"

xset r rate 200 30
setxkbmap -option ctrl:nocaps

pkill -9 dunst
