#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

readonly KEY="$1";
readonly TAGFILE="$HOME/.config/sxiv/tags"
readonly TMPFILE="/tmp/sxiv.$$"

tag_add() {
	>>"$TAGFILE"
	tags=$(dmenu <"$TAGFILE" | tr '\n' ',')
	[ -z "$tags" ] && return
	iptckwed -i -a "$tags"
	echo -n "$tags" | tr ',' '\n' | sort - "$TAGFILE" | uniq >"$TAGFILE.new"
	mv -f "$TAGFILE"{.new,}
}

tag_del() {
	cat >"$TMPFILE"
	tags=$(iptckwed -iql <"$TMPFILE" | cut -f 2 | tr ',' '\n' | sort | uniq | dmenu | tr '\n' ',')
	[ -z "$tags" ] && return
	iptckwed -i -r "$tags" <"$TMPFILE"
	rm -f "$TMPFILE"
}

case "$KEY" in
"d")        xargs -I{} mv -vf {} /tmp ;;
"C-d")      xargs -I{} mv -vf {} /tmp ;;
"y")        tr '\n' ' ' | xsel -b ;;
"C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
"C-t")      tag_add ;;
"M-T")      tag_del ;;
esac
