#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

pacaur --noconfirm --noedit --needed -Sr - < $DIR/state/pkglist.txt
pacaur --noconfirm --noedit --needed -S - < $DIR/state/aurlist.txt
pacaur --noconfirm -Rsu $(comm -23 <(pacman -Qq | sort) <(sort $DIR/state/pkglist.txt $DIR/state/aurlist.txt))

sudo cp -i -r $DIR/state/fslayer/* /

for srvc in $(cat $DIR/state/srvclist.txt); do
  sudo systemctl enable $srvc
done

