#!/bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )/.." && pwd )"

mkdir -p "$DIR/state"

find /etc/systemd/system/*.wants/ -name '*.service' | cut -d'/' -f6 | grep -v '@' > "$DIR/state/srvclist.txt"
yay -Qqn > "$DIR/state/pkglist.txt"
yay -Qqm > "$DIR/state/aurlist.txt"

for f in $(find "$DIR/state/fslayer" -type f | sed "s=$DIR/state/fslayer==g"); do
  sudo cp -rf "$f" "$DIR/state/fslayer$f"
  sudo chown "$LOGNAME:" "$DIR/state/fslayer$f"
done
