gui:
  nerdFontsVersion: "3"
  border: bold
  filterMode: fuzzy
  sidePanelWidth: 0.35
  timeFormat: "2006-01-02"
  shortTimeFormat: 15:04
  branchColorPatterns:
    "^luan/": "#FF9CFF" # use a light blue for branches beginning with 'docs/'
  spinner:
    # The frames of the spinner animation.
    frames:
      - 
      - 
      - 
      - 
      - 
      - 

    # The "speed" of the spinner in milliseconds.
    rate: 50

git:
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never --24-bit-color=never
customCommands:
  - key: "Y"
    context: "global"
    description: "Git Town sYnc"
    command: "git town sync --all"
    loadingText: "Syncing"
  - key: "U"
    context: "global"
    description: "Git Town Undo (undo the last Git Town command)"
    command: "git-town undo"
    prompts:
      - type: "confirm"
        title: "Undo Last Command"
        body: "Are you sure you want to Undo the last Git Town command?"
    loadingText: "Undoing Git Town Command"
  - key: "!"
    context: "global"
    description: "Git Town Repo (opens the repo link)"
    command: "git-town repo"
    loadingText: "Opening Repo Link"
  - key: "a"
    context: "localBranches"
    description: "Git Town Append"
    prompts:
      - type: "input"
        title: "Enter name of new child branch. Branches off of '{{.CheckedOutBranch.Name}}'"
        key: "BranchName"
    command: "git-town append {{.Form.BranchName}}"
    loadingText: "Appending"
  - key: "h"
    context: "localBranches"
    description: "Git Town Hack (creates a new branch)"
    prompts:
      - type: "input"
        title: "Enter name of new branch. Branches off of 'Main'"
        key: "BranchName"
    command: "git-town hack {{.Form.BranchName}}"
    loadingText: "Hacking"
  - key: "K"
    context: "localBranches"
    description: "Git Town Delete (deletes the current feature branch and sYnc)"
    command: "git-town delete"
    prompts:
      - type: "confirm"
        title: "Delete current feature branch"
        body: "Are you sure you want to delete the current feature branch?"
    loadingText: "Deleting Feature Branch"
  - key: "#"
    context: "localBranches"
    description: "Git Town Propose (creates a pull request)"
    command: "git-town propose"
    loadingText: "Creating pull request"
  - key: "p"
    context: "localBranches"
    description: "Git Town Prepend (creates a branch between the curent branch and its parent)"
    prompts:
      - type: "input"
        title: "Enter name of the for child branch between '{{.CheckedOutBranch.Name}}' and its parent"
        key: "BranchName"
    command: "git-town prepend {{.Form.BranchName}}"
    loadingText: "Prepending"
  - key: "S"
    context: "localBranches"
    description: "Git Town Skip (skip branch with merge conflicts when syncing)"
    command: "git-town skip"
    loadingText: "Skiping"
  - key: "G"
    context: "files"
    description: "Git Town GO aka:continue (continue after resolving merge conflicts)"
    command: "git-town continue"
    loadingText: "Continuing"
