gui:
  nerdFontsVersion: "3"
  border: bold
  filterMode: fuzzy
  sidePanelWidth: 0.35
  timeFormat: "2006-01-02"
  shortTimeFormat: 15:04
  authorColors:
    "Luan Santos": "#FF9CFF" # use a light blue for branches beginning with 'docs/'
  branchColorPatterns:
    "^luan/": "#FF9CFF" # use a light blue for branches beginning with 'docs/'
  spinner:
    # The frames of the spinner animation.
    frames:
      - 
      - 
      - 
      - 
      - 
      - 

    # The "speed" of the spinner in milliseconds.
    rate: 50

git:
  overrideGpg: true
  branchPrefix: "luan/"
  paging:
    colorArg: always
    pager: delta -s --dark --paging=never --24-bit-color=never
